### PR TITLE
Split Docker build for efficiency

### LINKED ISSUE #28: Split Python dependencies installation from project installation in Docker build
In current Dockerfile, program and its dependencies are installed in the same layer: https://github.com/openzim/_python-bootstrap/blob/c02d44f76f0bdb85f78998ec0ffc13fb38b8a5a0/Dockerfile#L17-L19

This layer is rebuild **everytime** code, config or documentation are changed : https://github.com/openzim/_python-bootstrap/blob/c02d44f76f0bdb85f78998ec0ffc13fb38b8a5a0/Dockerfile#L13-L15

However:
- this layer is "big" (e.g. 19Mo in `freecodecamp`, 260Mo in `gutenberg`) in most scrapers
- this layer takes time to build (many web resources to fetch at least)

Rebuilding this layer everytime code change looks like a waste of time (especially for the developer, but also in terms of computing resources) and storage (we re-upload the whole layer to ghcr.io everytime the branch is modified in a pull request and intermediate image versions might be kept on the developer machine).

### PR DESCRIPTION
**Pull request by benoit74**
Fix #28 

## Changes
- Program installation in Dockerfile is now separated in two phases / layers ; one for Python dependencies, one for the program itself

### CODE REVIEW

**Review by rgaudin — APPROVED** [review]
I am approving this because I think it will improve development experience but I don't like it.

- some _arguments_ in the issue are _far fetched_
- grouping install steps into a single `RUN` is the (Docker-)recommended way. Makes sense from an infrastructure stand-point, in a distribution approach: burden is left on the creator. That's also our general (Kiwix) approach.
- Using a third party tool to generate that previous format we've happily dropped feels odd. The fact that we need to bring in some additional stuff (like the about for metadata) feels hackish.

Let's use this until something better comes out

**Comment by benoit74** [comment]
I don't get why you consider some arguments of the issue are far fetched, this is just misunderstanding / wrong formulation from my PoV.

I don't agree that grouping install steps is the (Docker-)recommended way: see [here](https://docs.docker.com/build/cache/#order-your-layers) or [here](https://www.docker.com/blog/speed-up-your-development-flow-with-these-dockerfile-best-practices/) ; from my understanding, it is only recommended to group stuff which is strongly linked (e.g. do not install multiple apt packages with multiple RUN commands).

I agree that the extra tool is a shame. Since you insisted (thank you for that) I dig a bit and finally found the proper way to `pip install` from a `pyproject.toml` directly. I don't know why I failed to do it in the first place (probably because I misinterpreted the error message when `__about__.py` is missing).

**Review by rgaudin — APPROVED** [review]
Thanks ; that's a lot better! (IMO)

**Comment by benoit74** [comment]
It is !

**Pull request merged**
