### PR TITLE
Add debugpy to dependencies.

### LINKED ISSUE #10: Use `debugpy` as the Debug Adapter Protocol tools.
[debugpy](https://github.com/microsoft/debugpy) is a convenient tool that let all the text editors which support DAP can debug the Python program. Since we will inevitably use a virtual environment, I propose that we add `debugpy` to `dev` to facilitate debugging.

### PR DESCRIPTION
**Pull request by FledgeXu**
Fix #10.

### CODE REVIEW

**Comment by rgaudin** [comment]
Thank you ; could you provide some brief doc on how to use it?
- what editor and plugin are needed (I could only make it work with VSCode).
- sample invoke task to lauch a project with it enabled?
- How does it integrates with the editor? Can you set breakpoints directly in the UI or must them be set in the code?

**Comment by FledgeXu** [comment]
Sure, but where should I add the document?

**Comment by rgaudin** [comment]
Here's fine. I wonder if some might get into the repo or if it's only gonna be in the Wiki

**Comment by rgaudin** [comment]
OK then I think we're OK for now.

**Review by rgaudin — APPROVED** [review]

**Pull request merged**
